Pytorch 是一个基于 Python 的科学计算框架，它是：

1. 替代 Numpy 以使用 GPU 进行计算的框架
2. 一个灵活高效的深度学习研究平台

## Getting Started

### Tensors

> 张量 `Tensor` 和 Numpy 的 `ndarray` 是类似的，区别在于  `Tensor` 可以使用 GPU 来加速运算。

In [9]:
import torch

# torch.empty() 可以接受任意个位置参数，都会作为其 size 被传入
# empty() 指的是未初始化，并不一定是 0
# dtype 默认是 torch.float32
# requires_grad 默认是 False
x = torch.empty(5, 3, dtype=torch.int)
print(x)

tensor([[  57295296,          0,         32],
        [         0,         -1, 1919377267],
        [ 875772209, 1681285730, 1700999478],
        [ 929313588,  959657529,  926508385],
        [ 909586743,  929194801,          0]], dtype=torch.int32)


创建张量的操作还有：
- `torch.rand()`  均匀分布
- `torch.zeros()` 全 0 
- `torch.ones()` 全 1

其他 Creation Ops 见 [Creation Ops](https://pytorch.org/docs/stable/torch.html#creation-ops)

dtype 有：

- torch.float/double/half, 分别是 float32/64/128 的 alias
- torch.uint8
- torch.int8
- torch.short/int/long, 分别是 int16/32/64 的 alias

注意某些 Create Ops 不支持特定类型的 dtype：如 rand() 不支持设置 dtype 为整型

> `Tensor()` 方法可以使用已有的数据创建 `Tensor`

In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


> 也可以使用一个已有的 `Tensor` 来创建新的 `Tensor`

In [11]:
x = x.new_ones(5, 3, dtype=torch.double) # new 方法的第一个（组）参数是 sizes
print(x)

x = torch.randn_like(x, dtype = torch.float) # like 方法的 第一个参数是一个 Tensor
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2946,  1.0456, -1.5647],
        [ 0.4752, -0.3783,  1.0725],
        [-0.8837, -0.3588,  1.1728],
        [ 0.2643, -1.6873, -0.2031],
        [ 0.9122, -0.6149,  1.2947]])


**注意 `new_ones()` 和 `randn_like()` 都是 `Tensor` 的方法而不是 `torch` 的方法。**

new 方法还有：
- `new_tensor()`
- `new_zeros()`
- `new_full()` 第二个参数是 fill_value, 因此 size 必须用 tuple 的方式传入
- `new_empty()`

like 方法还有（）：
- `ones_like()`
- `zeros_like()`
- `empty_like()`
- `full_like()` 第二个参数是 fill_value
- `randn_like()`
- `randint_like()`

参数和含义不言自明

> 使用 `size()` 方法获取 `Tensor` 的 size

In [12]:
print(x.size())

torch.Size([5, 3])


## Operations

> pytorch 的运算符可以有多种写法，下面演示加法运算的三种写法

In [14]:
# syntax 1

y = torch.rand(5, 3)
print(x + y)

# syntax 2
print(torch.add(x, y))

# torch.add() 方法是 out-of-place 方法，返回结果的一个拷贝
# 可以显式指定结果输出到某个 Tensor
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# torch.add_() 方法是 add() 方法的 In-place 实现，会修改原 Tensor
y.add_(x)
print(y)

tensor([[-0.0793,  1.9369, -1.3093],
        [ 1.1482,  0.6042,  1.7828],
        [-0.5631,  0.2925,  2.1060],
        [ 0.7887, -1.5744,  0.0134],
        [ 1.4497, -0.3362,  1.4013]])
tensor([[-0.0793,  1.9369, -1.3093],
        [ 1.1482,  0.6042,  1.7828],
        [-0.5631,  0.2925,  2.1060],
        [ 0.7887, -1.5744,  0.0134],
        [ 1.4497, -0.3362,  1.4013]])
tensor([[-0.0793,  1.9369, -1.3093],
        [ 1.1482,  0.6042,  1.7828],
        [-0.5631,  0.2925,  2.1060],
        [ 0.7887, -1.5744,  0.0134],
        [ 1.4497, -0.3362,  1.4013]])
tensor([[-0.0793,  1.9369, -1.3093],
        [ 1.1482,  0.6042,  1.7828],
        [-0.5631,  0.2925,  2.1060],
        [ 0.7887, -1.5744,  0.0134],
        [ 1.4497, -0.3362,  1.4013]])


> Pytorch 中的 In-place 方法都在是 out-of-place 方法后面添加下划线 `_`，比如 `x.copy_(y)` 和 `x.t_(y)` 都会改变 x

> `Tensor` 支持使用 numpy-like 的 indexing 

In [18]:
print(x[:, 1]) # 选择第一列（下标从 0 开始）

torch.Size([5])


> 如果需要 resize/reshape 一个 `Tensor`, 使用 `torch.view()` 方法。该方法返回一个视图（引用），对引用的修改会影响原 `Tensor`

In [19]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # 标注 -1 的维会自动推断长度

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
# 修改视图会影响原数组
y[0] = y[1] = 1
print(x, y, z, sep='\n')

tensor([[ 1.0000,  1.0000,  0.0283,  1.7525],
        [-0.0878,  0.7748,  0.6290,  1.5902],
        [ 1.5881, -0.3212, -0.4184, -0.6173],
        [-0.2075,  0.7519, -2.6151, -0.7988]])
tensor([ 1.0000,  1.0000,  0.0283,  1.7525, -0.0878,  0.7748,  0.6290,  1.5902,
         1.5881, -0.3212, -0.4184, -0.6173, -0.2075,  0.7519, -2.6151, -0.7988])
tensor([[ 1.0000,  1.0000,  0.0283,  1.7525, -0.0878,  0.7748,  0.6290,  1.5902],
        [ 1.5881, -0.3212, -0.4184, -0.6173, -0.2075,  0.7519, -2.6151, -0.7988]])


> 使用 `Tensor.item()` 方法可以将单值 `Tensor` 变为标量

In [24]:
x = torch.randn(1)
print(x, x.item(), sep='\n')

tensor([-0.0736])
-0.0735730454325676


## Numpy Bridge

很容易可以在 Numpy array 和 `Tensor` 之间相互转换，注意转换前后的两者共享存储，修改其一会影响另一者。

### Tensor 转换为 Numpy Array

> 使用 `Tensor.numpy()` 方法可以将 `Tensor` 转换为 Numpy Array

In [25]:
a = torch.ones(5)
b = a.numpy()
print('Tensor     :', a)
print('Numpy Array:', b)

Tensor     : tensor([1., 1., 1., 1., 1.])
Numpy Array: [1. 1. 1. 1. 1.]


In [26]:
# 修改 a 会影响 b
a.add_(1) # 这里会触发广播
print('Tensor     :', a)
print('Numpy Array:', b)

Tensor     : tensor([2., 2., 2., 2., 2.])
Numpy Array: [2. 2. 2. 2. 2.]


### Numpy Array 转换为 Tensor

> 使用 `torch.from_numpy()` 可以将 Numpy Array 转换为 `Tensor`. 注意两个方向上的转换都不是使用 Numpy 的方法

In [27]:
import numpy as np


a = np.ones(5) # 注意 np.ones() 默认的 dtype 是 float64
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print('Numpy Array:', a)
print('Tensor     :', b) # 转换后的 dtype 也是 float64

Numpy Array: [2. 2. 2. 2. 2.]
Tensor     : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

`Tensor` 可以使用 `.to()` 方法移动到任意的 `device` 上，比如 CUDA

`.to()` 方法可以同时更改 `Tensor` 存储的设备位置和 dtype

In [3]:
import torch


if torch.cuda.is_available(): # CUDA 存在时才运行
    device = torch.device("cuda") # 获取默认的 cuda 设备
    x = torch.randn(1) # x 此时是在 CPU 上
    y = torch.ones_like(x, device=device) # y 在 GPU 上
    x = x.to(device) # 使用 .to() 方法将 x 送往 GPU
    z = x + y # 在 GPU 上执行运算，z 默认存放在 GPU 上 
    print(z)
    print(z.to('cpu', torch.double)) # 将 z 送往 CPU，同时更改 dtype

tensor([1.9882], device='cuda:0')
tensor([1.9882], dtype=torch.float64)
